### ISSUE TITLE
Problem: embedded PCRE code is very outdated

### ISSUE THREAD

**Issue by bluca** [zeromq/gsl#1]
From the pcre/NEWS file is looks like it's version 6.5 from 01-Feb-06, more than 10 years ago. PCRE has had a few CVEs in the meanwhile.

Thanks to @jimklimov work now at least on Linux we can build and link against the system library rather than the embedded one, but for Windows and other OSes users this problem should really be fixed.

**Comment by evoskuil** [comment]
FYI I've been building the Windows version against the [NuGet PCRE v8.33.0.1 package](https://www.nuget.org/packages/pcre/) for a few years now.

**Comment by bluca** [comment]
That's great, any chance you could add instructions to the README? Then if we've got all platforms covered we can simply remove the embedded version

**Comment by evoskuil** [comment]
The Visual Studio solutions already incorporate the NuGet references. This won't specifically help other platforms like MacOS or Windows builds that don't use Visual Studio.

But my point is that GSL does link properly with a fairly recent version. In fact, we do not build PCRE for linux/MacOS platforms either. See the [libbitcoin-build](https://github.com/libbitcoin/libbitcoin-build/blob/master/.travis.yml#L21-L29) Travis script.

I'm a little confused by PCRE versioning however, since [this site](http://www.pcre.org) states that PCRE2 is latest (2015) but we are using PCRE3 on Travis and the NuGet package is from 2013.

**Comment by bluca** [comment]
Yes PCRE versioning is quite confusing. But libpcre-dev is still maintained so it should be safe.

On OSX brew can install pcre apparently: ```brew install pcre```

Is building on Windows without VS supported in any way?

**Comment by bluca** [comment]
Yes OSX works just fine with pcre from brew. Just tried on the CI, PR incoming.

**Comment by jimklimov** [comment]
@bluca - Actually it was another way around: I saw that there is a dump of PCRE in the codebase with no easy way to build it and to build `gsl` against it, so I automated that - mostly for the kicks of testing if it builds at all, and if it passes the tests.

I believe it was possible to build against system library long before my improvements in the area (though lacking a real autotools or equivalent in GSL codebase, it might have problems finding something in not-default/expected paths). And I think it is the way it's built everywhere, unless someone went through deliberate adventure of building with bundled PCRE for their packaging.

**Comment by bluca** [comment]
Ok that's even better, thanks!

So I propose we remove it then. If for any reason it's needed again, there's the old repository and also the previously tagged versions.

I want to upload the package to debian, and that will make my life much easier as I won't need to repack the tarball before the upload.

What do you think?

**Comment by jimklimov** [comment]
No strong objections. I wonder what the original rationale for co-bundling was? Could it be e.g. nicer for constrained/embedded platforms, to have a more monolithic binary linking just the routines it uses? Did GSL actively run on those systems? :\

**Comment by evoskuil** [comment]
> Is building on Windows without VS supported in any way?

I assume so, but I only use the VS packages on Windows.

**Comment by bluca** [comment]
Ok then, opened a PR to jettison it :-)

**Comment by bluca** [comment]
@evoskuil @jimklimov I'll tag a new version, so I can then upload to Debian
