### ISSUE TITLE
Memory tag error when using different repository than github.com

### ISSUE THREAD

**Issue by vyskocilm** [zeromq/gsl#11]
Hi,

I ran into really weird issue with gsl, zproject and travis target. So far the minimal reproducer case is

```
    &lt;project
        name = "dbg"
        script = "zproject.gsl"
        repository = "https://github.com">

    <target name = "redhat" />
    <target name = "travis" />
    
   &lt;/project>
```

Running gsl file.xml works well. But once I change repository content, like "https://bitbucket.org", "https://gitlab.com", "git@github.com", "https://github.co.uk", then you will get gsl error

```
gsl/4 M: Generating skeleton .travis.yml script

Memory tag error - 0x563c29d2f640 - <Unknown> (0)
Aborted (core dumped)
```

Used dependencies (I have OBS packages installed from git-draft project)
```
rpm -q zproject generator-scripting-language

zproject-1504557118.26bc68b-77.1.x86_64

generator-scripting-language-1504755625.c020d42-13.1.x86_64
```

**Comment by c-rack** [comment]
I can confirm this with the following minimal GSL file:

```
a = "git@github.com"
b = string.search_replace (a, "https://github.com/", "https://api.github.com/repos/")
echo "$(b)"
```

Seems to be a bug in the string_replace function:
https://github.com/zeromq/gsl/blob/master/src/ggstrn.c#L509

**Comment by bluca** [comment]
Thanks for the PR! Any chance that minimal GSL test could be added to the selftest?
