### ISSUE TITLE
Make error MacOS 12.1 

### ISSUE THREAD

**Issue by MythicalC** [zeromq/gsl#49]
Moving to my new mac (MacOS Monterrey 12.1) and trying to install getting 'pcre.h' file not found error. I have installed and then reinstalled pcre, also updated Xcode's command line tools but still having no love. Full error text below.

----
 ggpcre.c
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
ggpcre.c:54:10: fatal error: 'pcre.h' file not found
#include <pcre.h>
         ^~~~~~~~

**Comment by sphaero** [comment]
I'm not sure what include paths are used on your mac. What does this command output:
```
find / -name pcre.h
```

**Comment by MythicalC** [comment]
OK  after a lot of "Operations not permitted" the files were found in:

/opt/homebrew/include/pcre.h (this one is a shortcut to the path below)
/opt/homebrew/Cellar/pcre/8.45/include/pcre.h

Cheers,

MC

**Comment by MythicalC** [comment]
That seemed to work, I have a lot of warnings (see the attached log) and yes I am on one on the new models which has been an exciting adventure in incompatibilities and new bugs >_<

[MakeLog.txt](https://github.com/zeromq/gsl/files/7930436/MakeLog.txt)

With the install I now get  the multiple symbols error (text below) which seems to be OS related, which means is *should* still work we might just get unpredictable behaviour if there is errors in one and not the other >_<

```
objc[10208]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1e8206b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107d602c8). One of the two will be used. Which one is undefined.
objc[10208]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1e8206be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107d60318). One of the two will be used. Which one is undefined.
```
