### ISSUE TITLE
Problem: Cross compilation is still not available by default

### ISSUE THREAD

**Issue by Vaelatern** [zeromq/gsl#6]
```
CCNAME='arm-linux-gnueabihf-gcc' ./c -q -r libgsl.a ggobjt.o ggcomm.o ggscop.o ggcode.o ggcodem.o ggpars.o ggparsm.o ggconv.o ggdiag.o ggenvt.o ggfile.o gggsl.o ggmath.o ggpcre.o ggproc.o ggscrp.o ggsock.o ggstrn.o ggsymb.o ggthrd.o ggtime.o ggxml.o sflbits.o sflcvds.o sflcvts.o sflfile.o sfllbuf.o sflnode.o sflsock.o sfltron.o smtlog.o smtmsg.o smtsimu.o smttst2.o sflcomp.o sflcvns.o sfldate.o sflfind.o sfllist.o sflprint.o
sflsort.o sfluid.o smtoper.o smtslot.o smttst3.o sflcons.o sflcvsb.o sfldes.o sflfort.o sflmail.o sflproc.o sflstr.o sflxml.o smtpipe.o smtsmtp.o smtxlog.o sflconv.o sflcvsd.o sfldescr.o sflheap.o sflmath.o sflscrit.o sflsymb.o sflxmll.o smtpop.o smtsock.o sflcryp.o sflcvsn.o sfldir.o
sflhttp.o sflmem.o sflsearch.o sflsyst.o sflxmls.o smtrdns.o smttime.o sflcvbs.o sflcvst.o sflenv.o sflini.o sflmesg.o sflsha.o sfltok.o smtecho.o smtrdnsl.o smttran.o sflcvdp.o sflcvtp.o sflexdr.o sfllang.o sflmime.o sflslot.o sfltree.o smtlib.o smtserv.o smttst1.o
CCNAME='arm-linux-gnueabihf-gcc' ./c -q -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2  -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard   -I/usr/arm-linux-gnueabihf/usr/include -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -L/usr/arm-linux-gnueabihf/usr/lib  -L gsl
./gsl -v
./gsl: ./gsl: cannot execute binary file
make: *** [Makefile:188: everything] Error 126
```

Even though the build is successful, being unable to execute across architectures makes gsl impractical to cross-build.

**Comment by bluca** [comment]
I think think supporting this will require switching to autotools.
Out of curiosity, what's your use case?

**Comment by jimklimov** [comment]
Just in case, I assume your system is set up to parse ARM binaries through a `qemu-arm-static` - right?

Does `file gsl` report it is an ARM or host-system (e.g. x86_64) binary?

I did build it (more for fun than work) with Linaro GCC cross-compiler. There were some quirks though, because indeed by default the script just uses `cc` and builds the host-system architecture binary.

As an excerpt from https://github.com/42ity/FTY/blob/master/Makefile-local-Linux-armv7l.mk and https://github.com/42ity/FTY/blob/master/Makefile I think the important bits were:

````
CROSS_PREFIX = arm-linux-gnueabihf
CROSS_COMPILE_PREFIX = $(CROSS_PREFIX)-
export CROSS_COMPILE_PREFIX
export CROSS_PREFIX

CC=$(CCACHE) $(CROSS_COMPILE_PREFIX)gcc
CXX=$(CCACHE) $(CROSS_COMPILE_PREFIX)g++
AR=$(CROSS_COMPILE_PREFIX)ar
LD=$(CROSS_COMPILE_PREFIX)ld
NM=$(CROSS_COMPILE_PREFIX)nm
STRIP=$(CROSS_COMPILE_PREFIX)strip
OBJDUMP=$(CROSS_COMPILE_PREFIX)objdump
OBJCOPY=$(CROSS_COMPILE_PREFIX)objcopy
RANLIB=$(CROSS_COMPILE_PREFIX)ranlib
AS=$(CROSS_COMPILE_PREFIX)as
export CC
export CXX
export AR
export LD
export NM
export STRIP
export OBJDUMP
export OBJCOPY
export RANLIB
export AS

# Custom options for gsl
MAKE_COMMON_ARGS_gsl = CCNAME="$(CC)" CCPLUS="$(CXX)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)"
````

Possibly the hacks into `PATH`, `LDFLAGS` and `CFLAGS` in the Makefile linked above could also play their role.

**Comment by Vaelatern** [comment]
My use case is building the package for Void Linux, where we cross build for any architecture we support if we don't have native dedicated builders.
To do that, we have quite a cool script, xbps-src, used by others in some cases http://landhere.galois.com/ but that reliably cross builds such huge packages as zfs and chromium/firefox.
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/gsl-ucg/template
No, we do not spin up qemu for these cross building jobs.

**Comment by Vaelatern** [comment]
In a sample cross build for armv7, @jimklimov
 
```
CCNAME='armv7l-linux-gnueabihf-gcc' ./c -q     -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2  -O2 -pipe -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard   -I/usr/armv7l-linux-gnueabihf/usr/include  sflcvsd.c
``` is an example of the build lines that built gsl in this case.

```
$ file ./gsl
./gsl: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=d7610be5755123b88861ed3ea841bca89f9188c0, with debug_info, not stripped
```

Part of the reason it's not stripped is because that happens after the build is done. The build isn't done because the Makefile concludes with `./gsl -v`.

Indeed, after applying the following patch, the build worked. Would this patch be accepted as a PR?
```
--- src/Makefile.bck    2017-09-06 02:54:04.375680332 -0400
+++ src/Makefile        2017-09-06 02:54:16.048706017 -0400
@@ -185,7 +185,6 @@
 smtxlog$(OBJ): smtxlog.c

 everything: libgsl$(LIB) gsl$(EXE)
-       ./gsl$(EXE) -v

 code:
        ./gsl$(EXE) -q ggconv.gxl ggdiag.gxl ggenvt.gxl ggfile.gxl gggsl.gxl ggmath.gxl ggpcre.gxl ggproc.gxl ggscrp.gxl ggsock.gxl ggstrn.gxl
ggsymb.gxl ggthrd.gxl ggtime.gxl ggxml.gxl

```

**Comment by bluca** [comment]
Yes that's just fine, we can add a gsl -v in the CI to check what it prints, doesn't have to be in the Makefile.

**Comment by jimklimov** [comment]
Could also move to a `check` recipe/target.

**Comment by Vaelatern** [comment]
I'll PR a patch I think will satisfy this.
